### PR TITLE
6730: Fix excluded dates ignored in YYYY-MM-DD HH:mm:ss date format in gantt diagram

### LINKED ISSUE #6730: Dates in excludes are ignored in Gantt diagrams when dateFormat is 'YYYY-MM-DD HH:mm:ss'
### Description

In Gantt diagrams, when dateFormat is 'YYYY-MM-DD HH:mm:ss', excluding specific dates are ignored.

### Steps to reproduce

a Gantt diagram code

```mermaid
gantt
    dateFormat YYYY-MM-DD HH:mm:ss
    excludes 2025-07-07
    section Section
        A task          :a1, 2025-07-04 20:30:30, 2025-07-08 10:30:30
        Another task    :after a1, 20h
```

Image

### Screenshots

_No response_

### Code Sample

```text

```

### Setup

- Mermaid version: 11.7.0
- Browser and Version: Firefox 128.12.0esr

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by darshanr0107**
## :bookmark_tabs: Summary

When using a Gantt diagram with `dateFormat: 'YYYY-MM-DD HH:mm:ss'`, the `excludes` dates (like weekends or specific days) were not being correctly matched. This PR fixes the issue.

Resolves #6730

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [ ] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

Before

Before

After
image

### CODE REVIEW

File: packages/mermaid/src/diagrams/gantt/ganttRenderer.js [hunk 1]
```diff
@@ -554,12 +554,14 @@ export const draw = function (text, id, version, diagObj) {
...
 
-    const dateFormat = diagObj.db.getDateFormat();
+    const normalizedExcludes = excludes.map((d) => dayjs(d).format('YYYY-MM-DD'));
+    const normalizedIncludes = includes.map((d) => dayjs(d).format('YYYY-MM-DD'));
     const excludeRanges = [];
     let range = null;
     let d = dayjs(minTime);
     while (d.valueOf() <= maxTime) {
-      if (diagObj.db.isInvalidDate(d, dateFormat, excludes, includes)) {
+      const dStr = d.format('YYYY-MM-DD');
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/gantt/ganttRenderer.js]: Use proper variable name.

File: cypress/integration/rendering/gantt.spec.js [hunk 2]
```diff
@@ -647,6 +647,20 @@ describe('Gantt diagram', () => {
...
+    gantt
+      dateFormat  YYYY-MM-DD HH:mm:ss
+      excludes    2025-07-07
+      section     Section
+      A task      :a1, 2025-07-04 20:30:30, 2025-07-08 10:30:30
+      Another task:after a1, 20h
+    `,
+      {}
+    );
+  });
```
Comment (sidharthv96) [inline cypress/integration/rendering/gantt.spec.js:662]: Can you add tests for other cases as well? Like weekends.

File: packages/mermaid/src/diagrams/gantt/ganttRenderer.js [hunk 3]
```diff
@@ -554,12 +554,14 @@ export const draw = function (text, id, version, diagObj) {
...
+      if (normalizedExcludes.includes(dStr) && !normalizedIncludes.includes(dStr)) {
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/gantt/ganttRenderer.js]: I feel this logic is better suited in the db, than the renderer. Is there a blocker to updating the logic inside `isInvalidDate`?

Also `isInvalidDate` is used in `fixTaskDates` function as well, so would we need changes there?

Comment (darshanr0107) [reply packages/mermaid/src/diagrams/gantt/ganttRenderer.js]: @sidharthv96 , resolved in https://github.com/mermaid-js/mermaid/pull/6734/commits/35a92efcdcc8eb990703f948a20556577856253c

File: cypress/integration/rendering/gantt.spec.js (hunk 2 above)
Comment (darshanr0107) [reply cypress/integration/rendering/gantt.spec.js:662]: @sidharthv96 , resolved in https://github.com/mermaid-js/mermaid/pull/6734/commits/35a92efcdcc8eb990703f948a20556577856253c

File: packages/mermaid/src/diagrams/gantt/ganttRenderer.js (hunk 1 above)
Comment (darshanr0107) [reply packages/mermaid/src/diagrams/gantt/ganttRenderer.js]: @sidharthv96 , resolved in https://github.com/mermaid-js/mermaid/pull/6734/commits/35a92efcdcc8eb990703f948a20556577856253c

File: .changeset/fuzzy-pears-cough.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'mermaid': patch
+---
+
+Fix: an issue where exclude dates in Gantt charts were ignored when using dateFormat: 'YYYY-MM-DD HH:mm:ss'.
```
Comment (sidharthv96) [inline .changeset/fuzzy-pears-cough.md]:
```suggestion
fix: handle exclude dates properly in Gantt charts when using dateFormat: 'YYYY-MM-DD HH:mm:ss'
```

Comment (darshanr0107) [reply .changeset/fuzzy-pears-cough.md]: resolved in 1176d306688323592879b11199ecbf0b69255358
