### PR TITLE
fix: Allow hollow markers on edges

### LINKED ISSUE #1687: Arrow of class diagram inheritance arrow missing
There are two options. 
* Introduce another arrow like --i> , --[>, --o>  or  --|:> 
* Change the black arrow --|> to be white

What do you think

### LINKED ISSUE #3816: Generalization relationship should be represented by a hollow triangle, not a solid one.
### Description

According to section **9.2.4.2 Other elements** in [the UML 2.5.1 Specificatiion](https://www.omg.org/spec/UML/2.5.1/PDF), 
A Generalization is shown as a line with a **hollow triangle as an arrowhead** between the symbols representing the involved Classifiers. The arrowhead points to the symbol representing the general Classifier. 

The models on the [Mermaid webpage](https://mermaid.live/edit#pako:eNptkc9OwzAMxl8l8omJ9QWqXRBjEgdOu6FIyE1MFzVxIH80wdi7k3Y0jI2c7J_zWZ_tAyivCVpQFmNcG-wDOsmivDs2Dq1YfTWNWGc1XNONibtr-kxdwD-4FbeGk8CeLvE2BcO96Ik1hfPiKIlP6Ep4s7goOEw0w8n2ZO9wAqI27QiHe299qIW4N24WlvQ9oxrm_Hjebxys9mtG79F80iNviFLFCvkB07_6aQW_hjrvrTDxZW-srjBkrlpYgqPg0OhyiUknIe3IkYS2hJpeMdskQfL4FXPy2w9W0KaQaQn5TZeN_NzuBI_fJHSQVA) are drawing them as solid.

### Steps to reproduce

Draw any subclass relationship.

### Screenshots

image

### Code Sample

_No response_

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sidharthv96**
## :bookmark_tabs: Summary

Moves the arrow markers on the line so that the line doesn't pass through the marker. Allowing it to be transparent.

Resolves #3816
Resolves #1687

Based on the work done by @jgreywolf on https://github.com/mermaid-js/mermaid/pull/4582. 

## :straight_ruler: Design Decisions

Currently, we shorten the line drawn by an offset, and move the marker to the end of the line, so that the line does not pass through the marker. 

Shortening of the line is one part where some easier logic could be used. 

image

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [ ] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/dagre-wrapper/markers.js [hunk 1]
```diff
@@ -125,15 +125,31 @@ const lollipop = (elem, type) => {
...
+    .attr('markerWidth', 190)
+    .attr('markerHeight', 240)
+    .attr('orient', 'auto')
+    .append('circle')
+    .attr('stroke', 'black')
+    .attr('fill', 'transparent')
+    .attr('cx', 7)
+    .attr('cy', 7)
+    .attr('r', 6);
+  elem
```
Comment (aloisklink) [inline packages/mermaid/src/dagre-wrapper/markers.js:139]:
```suggestion

  elem
```

Everywhere else has in this file seems to have a space separate calls to `elem.append()`.

File: packages/mermaid/src/dagre-wrapper/edges.js [hunk 2]
```diff
@@ -435,22 +448,59 @@ export const insertEdge = function (elem, e, edge, clusterDb, diagramType, graph
...
-  if (diagramType === 'graph' || diagramType === 'flowchart') {
-    curve = edge.curve || curveBasis;
-  } else {
-    curve = curveBasis;
+  if (edge.curve && (diagramType === 'graph' || diagramType === 'flowchart')) {
+    curve = edge.curve;
   }
-  // curve = curveLinear;
+
+  // The offsets are calculated from the markers' dimensions.
```
Comment (aloisklink) [inline packages/mermaid/src/dagre-wrapper/edges.js:459]:
```suggestion
  // We need to draw the lines a bit shorter to avoid drawing
  // under any transparent markers.
  // The offsets are calculated from the markers' dimensions.
```

**Review by aloisklink — COMMENTED** [review]
Wow! This solution definitely seems nicer than the workaround in https://github.com/mermaid-js/mermaid/pull/4582 (even if the math magic is a bit less maintainable). Amazing work getting all the math working!

I'll let @jgreywolf give a proper review of this PR, since the last time I touched class UML diagrams was years ago in high-school, so I'm really unfamiliar with it :laughing:

**Review by jgreywolf — APPROVED** [review]

**Review by knsv — APPROVED** [review]
