### PR TITLE
Fix exceptions for empty lines

### LINKED ISSUE #4280: v10.1.0 Regression: Unexpected svg element not in render tree error
### Description

Looks like there is an issue in https://github.com/mermaid-js/mermaid/commit/4d1d1c36de1276f179d653b073553e02878f530e where if you are measuring an empty text, Mermaid v10.1.0 throws an error of "svg element not in render tree" while the root element is in the DOM tree.

### Steps to reproduce

1. Go to https://codepen.io/luin/pen/zYmOXgv
2. Open console, there is an error "svg element not in render tree"

### Screenshots

_No response_

### Code Sample

```text
<body>
  <div id="graphDiv">chart</div>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10.1.0/dist/mermaid.esm.min.mjs';
    mermaid.initialize({
      startOnLoad: false,
      fontFamily: 'inherit',
    });
    const graphDefinition = `sequenceDiagram
    autonumber
    actor Application code
    participant Item 1
    participant Item 2
    participant Item 3
    Application code->>Item 1: Subscribe
    activate Item 1
    Item 1 ->> Item 1: Pause
    Item 1 ->> Item 2: Subscribe to block  <br> 
    activate Item 2
    Note over Item 1,Item 2: Uses some stuff
    Item 2 ->> Item 2: Save this
    Item 2 ->> Item 3: Request the next part from another component
    Item 3 -->> Item 2: Return the next part
    Item 2 -> Item 3: Request the data
    Item 3 ->> Item 2: Stream data 
    note over Item 2: Data streaming goes through Item 2, <br> but we want to avoid collecting the data here. <br> Item 2 is aware when the stream ends.
    Item 2 -->> Item 1: Stream data
    deactivate Item 2

    Item 1 -> Item 2: Resume 
    Item 2 --> Item 1: Stream 
    Item 1 --> Application code: Notify subscription successful
`;
    const drawDiagram = async function() {
      const element = document.querySelector('#graphDiv');
      const {
        svg,
      } = await mermaid.render('graphDiv', graphDefinition);
      element.innerHTML = svg;
    };
    drawDiagram().then(console.log, console.log);
  </script>
</body>
```

### Setup

- Mermaid version: v10.1.0
- Browser and Version: Chrome

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by luin**
## :bookmark_tabs: Summary

Ignore empty lines when calculating text dimensions. In https://github.com/mermaid-js/mermaid/issues/4180, we threw an exception when the text dimension is 0. However, besides the two reasons given in the ticket description, another cause is the text is empty.

Resolves #4280, #4298, #4293

## :straight_ruler: Design Decisions

This PR ignores empty lines. We already ignores empty text, but we didn't handle empty lines.

### :clipboard: Tasks

Make sure you

- [X] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [X] :computer: have added unit/e2e tests (if appropriate)
- [X] :notebook: have added documentation (if appropriate)
- [X] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/utils.ts [hunk 1]
```diff
@@ -764,6 +764,9 @@ export const calculateTextDimensions: (
       let cheight = 0;
       const dim = { width: 0, height: 0, lineHeight: 0 };
       for (const line of lines) {
+        if (!line) {
+          continue;
+        }
```
Comment (sidharthv96) [inline packages/mermaid/src/utils.ts:769]: Although this fixes the symptom, it doesn't solve the root cause of the issue. 
If we add `<br/><br/><br/>` it should render three empty lines, now, it seems like it won't render anything. 

Maybe, if we replace the `continue` with `line = ' ';`, it might work?

File: cypress/integration/rendering/sequencediagram.spec.js [hunk 2]
```diff
@@ -88,6 +88,16 @@ context('Sequence diagram', () => {
       {}
     );
   });
+  it('should handle empty lines', () => {
+    imgSnapshotTest(
+      `
+      sequenceDiagram
+      Alice->>John: Hello John<br/>
+      John-->>Alice: Great!
```
Comment (sidharthv96) [inline cypress/integration/rendering/sequencediagram.spec.js:96]:
```suggestion
      John-->>Alice: Great<br/><br/>day!
```

File: packages/mermaid/src/utils.ts (hunk 1 above)
Comment (luin) [reply packages/mermaid/src/utils.ts]: Makes sense! I end up with zero-width spaces as they don't occupy horizontal space and won't be collapsed inside DOM elements.

**Review by sidharthv96 — APPROVED** [review]
