### PR TITLE
fix Detect diagram fallback

### LINKED ISSUE #3391: Remove flowchart as default fallback in detectType.

### PR DESCRIPTION
**Pull request by sidharthv96**
## :bookmark_tabs: Summary

Removes `flowchart` as fallback for detectDiagram and throw error if diagram is not recognised.

Resolves #3391 

## :straight_ruler: Design Decisions

Will avoid ambiguity and wrong errors being thrown when flowchart is used.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/mermaid.ts [hunk 1]
```diff
@@ -247,9 +230,6 @@ const mermaid: {
   initialize: typeof initialize;
   contentLoaded: typeof contentLoaded;
   setParseErrorHandler: typeof setParseErrorHandler;
-  // Array of functions to use for detecting diagram types
-  detectors: Array<any>; // eslint-disable-line @typescript-eslint/no-explicit-any
-  connectDiagram: (id: string, diagram: DiagramDefinition, callback: (id: string) => void) => void;
```
Comment (sidharthv96) [inline packages/mermaid/src/mermaid.ts:252]: @knsv I've removed detectors and connect diagram for now as we're currently using lazyLoadedDiagrams.
We can introduce it later once we have nailed down the interface completely.

**Review by knsv — APPROVED** [review]
