### PR TITLE
Fix graph not loading when the img loads too fast or fail to load

### LINKED ISSUE #4439: Our graph is not working anymore since 10.2.0
### Description

Hello!
First, thanks for the great lib!

Our mermaid graph seems to be broken after we upgraded mermaid to 10.2.0.
**Before**
Screenshot 2023-05-30 at 13 55 27
**After**
Screenshot 2023-05-30 at 13 54 34

It looks like the svg doesn't have the viewbox anymore:
image

We have this config: 

```
{
  "maxTextSize": 800000,
  "startOnLoad": false,
  "securityLevel": "loose",
  "flowchart": {
    "useMaxWidth": true,
    "htmlLabels": true,
    "curve": "cardinal"
  },
  "theme": "dark"
}
```

Do you have any idea?

### Steps to reproduce

See above

### Screenshots

_No response_

### Code Sample

```text
(example here, but the live editor is not up to date with the latest version)

https://mermaid.live/edit#pako:eNrFVH9r2zAU_CpvGiVQYlzo0hiTpDR18lfKBi0MlpSgWM-1NtvyJDk_GvLdJ9nKsjSlgzKYDTK6O92TfPbbklgwJCF5krRM4SGaFQAa13r6YIZHO1tUWotiOqwfNcK4yrlSc8dEzRT-UJQ81pXE6ZfmWWNKbzJ0bpDwLAs_jsdRNLw6kMfGTjS6Hd2OxweR83ZsdDkeBcGBtXt31PBqfGEX2hvM1elOZ6SHOXDWbymNpdfptppl_VYiCu2tkD-lOoSFyFhrcD4UxXdRyXMIV3SJIYyU9mKEnxXCUlQKDPgMnyDnRaVRQWm0UFKZoQSGxliieSvXPR_zQW8hfTeYWSJrMIR_VWJvjIUzbhAKqcSk3_IpMw5-nFK9EHoeGxeFyr98gcztS1F-p-sj47o1GJmx59MBePBOqwJX168QZ51hKXHJzQnr-ZwzddaJDGzGvkllcMMYWMaWn5HHJsBmtEGC5w2gE-yT3YdviJfR1_rgJPjgreBvlhhDmVGuuIQPb-XXa77UkxUOfi0XxxxL3hlU8J-DCv4SlEslOPrdSZvkKHPKmWk7WyudkZyubb-55884IyEEF_ZqN5zSVOrPxURQZrmEZgr3FMaV5HozwSVmlpyRTAhlPJwgycTKHEtqS27d5kil8I6uv3KmU4trWTWGlkt1nk3oAjN1QplaS2yqxFQyXlBT05I7V02nmDsBo_KHJXfmtLTS4n5TxCRs9k6qklGNEaem6ea_URulkHdNO667cpuUtPgmhNHYjex-AVeT53U
```

### Setup

- Mermaid version: 10.2
- Browser and Version: Chrome

### Additional Context

Happy to help debug if needed

### PR DESCRIPTION
**Pull request by pierrickouw**
## :bookmark_tabs: Summary

The graph would never finish rendering when an img was present, but couldn't load.

Resolves #4439 

## :straight_ruler: Design Decisions

We check the `complete` attribute of the image, and listen for both the `load` and `error` event.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :notebook: have added documentation (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/dagre-wrapper/shapes/util.js [hunk 1]
```diff
@@ -82,8 +85,15 @@ export const labelHelper = async (parent, node, _classes, isNode) => {
                   img.style.width = '100%';
                 }
                 res(img);
-              })
-            )
+              }
+              setTimeout(() => {
```
Comment (pierrickouw) [inline packages/mermaid/src/dagre-wrapper/shapes/util.js:89]: Works well on chrome without this, Electron seems to be a bit different

Comment (sidharthv96) [reply packages/mermaid/src/dagre-wrapper/shapes/util.js:89]: What about firefox?

Comment (pierrickouw) [reply packages/mermaid/src/dagre-wrapper/shapes/util.js:89]: Worked fine too, it was really only Electron in test.
