### PR TITLE
Align arrows on sequence diagram

### LINKED ISSUE #4691: Improve arrow positions on sequence diagrams
### Description

Compared to most other sequence diagrams I've seen generated by other software, arrow heads in mermaid sequence diagrams are positioned differently. I would not necessarily say that the mermaid way is "wrong", but at least to my eyes it does look a bit "off" compared to what I'm used to seeing.

The largest difference is that arrow heads extend into activation boxes rather than end at the border of the box.
Also, at larger scales, the tip of the arrow heads seem to slightly shoot past the line that they point to when no activation box exist.
I have added two screenshots to illustrate how it looks now and how it might look if it was drawn like most examples I could find.

### Steps to reproduce

Link to the example used for the screenshots: [mermaid.live](https://mermaid.live/edit#pako:eNpNz1FPwyAQAOC_wu5V2lRWysrDjEYT9dU30xdsb2tjgclotDb970K7JfJAuLvvLscEtW0QJJzxa0BT42Onjk7pypBw7vuuxmS_v3m1rZHkGfvekvimpLXfRDkkox3uVhzz0T7YD0nCRUmtTKyTFpUjGi8ulJLgksvMbrUvi15kaNn8GxntsogM6IDYk6ND5TdAQaPTqmvC-lNsqMC3qLECGZ6Ncp8VVGYObjg1yuNT03nrQHo3IAU1ePs2mvoar-byfZAH1Z9D9qTMu7X6ikIIcoIfkIzxlAt2K_JMMFbwglEYQYoyFUJkZVlk5VbwmcLv0p6lO1bkebHlbCcYz4v5D_YccyI)

### Screenshots

Current look:
image

Mock-up:
image

### Code Sample

_No response_

### Setup

- Mermaid version: 10.3.0
- Browser and Version: Firefox 115.0.3

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sidharthv96**
### Before
image

image

image

### After
image

image

image

Resolves #4691

## :straight_ruler: Design Decisions

Instead of changing the complete rendering logic, a check has been added to check if we are not detecting an activation properly. 

The arrow lengths have also been shortened so that the edge markers can be pushed out properly.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/diagrams/sequence/sequenceDb.js [hunk 1]
```diff
@@ -530,7 +532,7 @@ export const apply = function (param) {
             lastDestroyed = undefined;
           }
         }
-        addSignal(param.from, param.to, param.msg, param.signalType);
+        addSignal(param.from, param.to, param.msg, param.signalType, param.activate);
```
Comment (aloisklink) [inline packages/mermaid/src/diagrams/sequence/sequenceDb.js:535]: I feel like we need to add a JSDoc comment for the `activate` value somewhere (although no functions in this file seem to have any comments).

Does it make sense to do something like:

```js
/**
 * @typedef {Object} AddMessageParams A message from one actor to another.
 * //TODO: add missing types
 * @property {"addMessage"} type - Set to `"addMessage"` if this is an `AddMessageParams`.
 * @property {boolean} [activate] - If `true`, this signal starts an activation.
 */

/**
 * @param {Object | AddMessageParams} param - Object of parameters.
 */
export const apply = function (param) {
```

We don't need to add types/documentation for everything (especially since this is still a JavaScript file, not TypeScript). Just having docs for the new `activate` param that you added is good enough.

File: packages/mermaid/src/diagrams/sequence/svgDraw.js [hunk 2]
```diff
@@ -703,7 +703,7 @@ export const insertArrowHead = function (elem) {
     .append('defs')
     .append('marker')
     .attr('id', 'arrowhead')
-    .attr('refX', 9)
+    .attr('refX', 7.9)
```
Comment (aloisklink) [inline packages/mermaid/src/diagrams/sequence/svgDraw.js:706]: `7.9` seems like a very weird number. I'm guessing this is the number that looks the best, but I just wanted to double-check that you didn't accidentally make a typo.

**Review by aloisklink — APPROVED** [review]
Looks good to me!

Good work on handling the `sequence.activationWidth` config value too `{"sequence": {"activationWidth": 40}}` :+1:

File: packages/mermaid/src/diagrams/sequence/svgDraw.js (hunk 2 above)
Comment (sidharthv96) [reply packages/mermaid/src/diagrams/sequence/svgDraw.js:706]: Nope, arrived at that value after the extremely scientific method of zooming in and looking closely while adjusting the value. 🧑‍🔬

**Review by knsv — APPROVED** [review]
Precision fix. Well done!
