### PR TITLE
remove SimpleMarkdown

### LINKED ISSUE #4302: `@khanacademy/simple-markdown` imposes peer dependency on an old version of react
### Description

When using `pnpm`:
```
 WARN  Issues with peer dependencies found
packages/swmd
└─┬ mermaid 10.1.0
  └─┬ @khanacademy/simple-markdown 0.8.6
    ├── ✕ missing peer react@16.14.0
    └── ✕ missing peer react-dom@16.14.0
Peer dependencies that should be installed:
  react-dom@16.14.0  react@16.14.0  
```

This is annoying, it forces projects to bring in react, and it forces them to an ancient version.

### Steps to reproduce

1. Install mermaid using `pnpm <=7`: `pnpm i mermaid`.

### Screenshots

_No response_

### Code Sample

_No response_

### Setup

- Mermaid version: 10.1.0
- Browser and Version: Chrome 112.0.5615.49

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sidharthv96**
## :bookmark_tabs: Summary

Supersedes #4343 based on reviews.
Replace @khanacademy/simple-markdown with micromark to avoid react peerDependency.
Resolves #4302

### Changed

- Unsupported Markdown formatting now results in `Unsupported markdown` being displayed in the Mermaid diagram.

## :straight_ruler: Design Decisions

Sole purpose is to remove the react peer dependency. 
Discussions regarding adding micromark, newlines, etc will continue in #4343 slotted for a future release. Maybe V11?

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :notebook: have added documentation (if appropriate)
- [ ] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
@aloisklink Tried the 2 separate commits idea, didn't work. :'( 

image

I have reverted is back to js, with jsdoc types for now.

File: packages/mermaid/src/rendering-util/handle-markdown-text.js [hunk 1]
```diff
@@ -65,30 +59,27 @@ export function markdownToLines(markdown) {
...
+      return `<strong>${node.children.map(output).join('')}</strong>`;
+    } else if (node.type === 'emphasis') {
+      return `<em>${node.children.map(output).join('')}</em>`;
     } else if (node.type === 'paragraph') {
-      return `<p>${node.content.map(output).join('')}</p>`;
-    } else {
-      return '';
+      return `<p>${node.children.map(output).join('')}</p>`;
     }
+    return `Unsupported markdown: ${node.type}`;
```
Comment (sidharthv96) [inline packages/mermaid/src/rendering-util/handle-markdown-text.js:81]: Only logic change is here. 
This will make the user aware that they are using unsupported markdown. 
Can remove once micromark is added to support complete html.

File: packages/mermaid/src/rendering-util/handle-markdown-text.js [hunk 2]
```diff
@@ -65,30 +59,27 @@ export function markdownToLines(markdown) {
...
 /**
- *
- * @param markdown
+ * @param {string} markdown markdown to convert to HTML
+ * @returns {string} HTML
  */
 export function markdownToHTML(markdown) {
-  const mdParse = SimpleMarkdown.defaultBlockParse;
-  const syntaxTree = mdParse(markdown);
+  const { children } = fromMarkdown(markdown);
```
Comment (sidharthv96) [inline packages/mermaid/src/rendering-util/handle-markdown-text.js:66]: @remcohaszing reused `fromMarkdown` in this PR to reduce the scope. 

It'll still have issues with newlines, but we can resolve that in https://github.com/mermaid-js/mermaid/pull/4343 

The plan is to remove the react peer dependency in this release and properly fix the newline issues in a future release.

**Review by aloisklink — APPROVED** [review]
Looks great! Thanks for reducing the scope in the PR :) Fully supporting every bit of the Markdown spec was a bit scary.

It might be worth putting the change in https://github.com/mermaid-js/mermaid/pull/4350/files#r1177360589 in the PR description too, something like:

```md
### Changed

- Unsupported Markdown formatting now results in
  `Unsupported markdown` being displayed in the Mermaid diagram.
```

---

> @aloisklink Tried the 2 separate commits idea, didn't work. :'( 

Actually, it did work, you just have to select each individual commit when reviewing the PR:

image

GitHub history also shows the rename too:

image

Other commands like `git rebase` and `git merge` should also realize there was a rename, so there will a lower chance of merge conflicts.

**Comment by sidharthv96** [comment]
> Actually, it did work, you just have to select each individual commit when reviewing the PR:

Ohh, I meant the PR changes tab which was still the same. Didn't think about checking individual commits.

File: packages/mermaid/src/rendering-util/handle-markdown-text.js (hunk 2 above)
Comment (remcohaszing) [reply packages/mermaid/src/rendering-util/handle-markdown-text.js:66]: FWIW I've created [`mdast-util-newline-to-break`](https://github.com/syntax-tree/mdast-util-newline-to-break).

File: packages/mermaid/src/rendering-util/handle-markdown-text.js (hunk 1 above)
Comment (knsv) [reply packages/mermaid/src/rendering-util/handle-markdown-text.js:81]: Sounds good!

**Comment by knsv** [comment]
Great job, thanks!

**Review by knsv — APPROVED** [review]
