### PR TITLE
Fix - static class attributes are not rendered underlined

### LINKED ISSUE #5009: Class attributes marked as static ($) don't render text-decoration: underline
### Description

Class diagrams with static attributes marked with '$' do not render as underlined.
This is can be reproduced in the live editor with the example below.
Methods which are marked as static with the '$' symbol or methods which are marked as abstract with the '\*' symbol are rendered correctly. Attributes which are marked as abstract with the '\*' are also rendered correctly. However Attributes which are marked as static with the '$' symbol are not rendered correctly. the text-decoration: underline is missing.

### Steps to reproduce

Open the following Link in the Live Editor

 [](https://mermaid.live/edit#pako:eNptkMEOgjAMhl9laTgo0RfYWT2pF667NKzgkg3IKImG8O4O3AwSe9nyf__fph2hbDWBhNJi358M1h6dakSoRRHnJ7rOkhg_4lxHUbA3TS0q43u-o6PsDwzpheWJrD3fpIz2nw4pmmC-hjXxJaV3-zQt21iuuHXEJhMcwJF3aHTYetlKAT_IkQIZvpoqHCwrUM1sxYHb4tWUINkPdICh08gU7wSyQtsHlbTh1t_iJednegNCXmki)

### Screenshots

_No response_

### Code Sample

```text
classDiagram
    class Example {
        - String firstName$
        - String lastName*        
        - firstName: String$
        - lastName: String*
        - getFirstName() String $
        - getLastName() String *
    }
```

### Setup

- Mermaid version: 10
- Browser and Version: [Chrome-117.0.5938.150, Edge-117.0.2045.60]

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SteffenLm**
## :bookmark_tabs: Summary

This PR fixes the incorrect rendering of static class attributes in a class diagram.

Resolves #5009 

## :straight_ruler: Design Decisions

It just fixes the regular expression which was wrong. Now it detects the right characters ('$' and '*').

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

Please let me know if i missed something!

### CODE REVIEW

**Review by jgreywolf — APPROVED** [review]

**Comment by SteffenLm** [comment]
@jgreywolf thanks for approving the PR but who can merge it?

File: packages/mermaid/src/diagrams/class/classTypes.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ export class ClassMember {
         this.visibility = firstChar as Visibility;
       }
 
-      if (lastChar.match(/[*?]/)) {
+      if (lastChar.match(/[$*]/)) {
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/class/classTypes.ts:109]: I'm not familiar with the specifics of class diagram syntax. Based on the docs, this change looks good.
But, doesn't this change break diagrams that had `?` previously? @knsv thoughts?

image

**Review by sidharthv96 — APPROVED** [review]
Nice work with the PR, love the tests. 
Would prefer to let @knsv decide regarding removing `?`.

File: packages/mermaid/src/diagrams/class/classTypes.ts (hunk 1 above)
Comment (SteffenLm) [reply packages/mermaid/src/diagrams/class/classTypes.ts:109]: Thanks! Idk if the `?` was done by accident. I use mermaid class diagrams since 2022 and never only used `*` and `$`.

Comment (knsv) [reply packages/mermaid/src/diagrams/class/classTypes.ts:109]: I agree this will be a problem for people using the question mark. However, that has been a "hidden feature" in the docs, we have been consistent since 2019 * and $. My interpretation is a mistake, and I think we can go ahead.

We could allow question marks as well, but let's keep it in sync with the docs as the first option. In the very unlikely event that this results in outrage, we can add it.

**Review by knsv — APPROVED** [review]
Let's do it!

File: packages/mermaid/src/diagrams/class/classTypes.ts (hunk 1 above)
Comment (aloisklink) [reply packages/mermaid/src/diagrams/class/classTypes.ts:109]: It looks like it was accidentally added in https://github.com/mermaid-js/mermaid/pull/4534, as it looks like `*` and `$` are the only two values that do anything in https://github.com/mermaid-js/mermaid/blob/05c2a11e3d265d99c21a1a190be75048c1c0e985/packages/mermaid/src/diagrams/class/classTypes.ts#L122-L131, so `/[$*]/` is correct!

Since the `?` doesn't seem to do anything currently, I believe this to be a safe change, even for people already using `?`.

**Review by aloisklink — APPROVED** [review]
Looks good to me too!
