### PR TITLE
chore: Fix spelling

### LINKED ISSUE #6501: Spelling errors
### Description

When I check repository spelling, I found mistakes

### Steps to reproduce

1. Add check-spelling workflow and tune it
2. Review final report https://github.com/jsoref/step-security-agent/actions/runs/14504304756#summary-40690719199

### Screenshots

_No response_

### Code Sample

```text

```

### Setup

- Mermaid version: develop

### Suggested Solutions

I'm going to make a PR

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jsoref**
## :bookmark_tabs: Summary

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling)

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/mermaid-js-mermaid/actions/runs/14525623283#summary-40756434277

- Resolves #6501 

## :straight_ruler: Design Decisions

I tried to replace typos with words/phrases that seemed more appropriate

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [ ] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/mermaid/src/diagrams/c4/c4Db.js [hunk 1]
```diff
@@ -705,6 +705,7 @@ export const getBoundaries = function (parentBoundary) {
   }
 };
 
+// cspell:ignore getBoundarys
```
Comment (jsoref) [inline packages/mermaid/src/diagrams/c4/c4Db.js:708]: This moved from `.cspell/code-terms.txt`

File: packages/mermaid/src/diagrams/c4/c4Renderer.js [hunk 2]
```diff
@@ -542,7 +542,7 @@ function drawInsideBoundary(
       );
     }
     parentBoundaryAlias = currentBoundary.alias;
-    let nextCurrentBoundaries = diagObj.db.getBoundarys(parentBoundaryAlias);
```
Comment (jsoref) [inline packages/mermaid/src/diagrams/c4/c4Renderer.js:545]: I'm hoping this is a consumer of the deprecated api

File: packages/mermaid/src/diagrams/common/common.spec.ts [hunk 3]
```diff
@@ -28,7 +28,7 @@ describe('when securityLevel is antiscript, all script must be removed', () => {
   it('should remove all javascript urls', () => {
     compareRemoveScript(
       `This is a <a href="javascript:runHijackingScript();">clean link</a> + <a href="javascript:runHijackingScript();">clean link</a>
-  and <a href="javascript&colon;bipassedMining();">me too</a>`,
+  and <a href="javascript&colon;bypassedMining();">me too</a>`,
```
Comment (jsoref) [inline packages/mermaid/src/diagrams/common/common.spec.ts:31]: afaict, this is an arbitrary nonexistent function...

File: packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md [hunk 4]
```diff
@@ -125,7 +125,7 @@ Cardinality is a property that describes how many elements of another entity can
...
+Relationships may be classified as either _identifying_ or _non-identifying_ and these are rendered with either solid or dashed lines respectively. This is relevant when one of the entities in question cannot have independent existence without the other. For example a firm that insures people to drive cars might need to store data on `NAMED-DRIVER`s. In modelling this we might start out by observing that a `CAR` can be driven by many `PERSON` instances, and a `PERSON` can drive many `CAR`s - both entities can exist without the other, so this is a non-identifying relationship that we might specify in Mermaid as: `PERSON }|..|{ CAR : "driver"`. Note the two dots in the middle of the relationship that will result in a dashed line being drawn between the two entities. But when this many-to-many relationship is resolved into two one-to-many relationships, we observe that a `NAMED-DRIVER` cannot exist without both a `PERSON` and a `CAR` - the relationships become identifying and would be specified using hyphens, which translate to a solid line:
```
Comment (jsoref) [inline packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md:128]:
```diff
-This is relevant when one of the entities in question can not have independent existence without the other\.
+This is relevant when one of the entities in question cannot have independent existence without the other\.
```

File: cypress/platform/yari2.html [hunk 5]
```diff
@@ -90,7 +90,7 @@ <h2>Basic Relationship</h2>
           erDiagram
             CAR ||--o{ NAMED-DRIVER : allows
             CAR {
-                test test PK "comment"
+                text text PK "comment"
```
[the remark this answers is not in the document]
Comment (sidharthv96) [reply cypress/platform/yari2.html:93]: This is a scratch file for developers (which ideally shouldn't be committed), so we can ignore the content in here.

**Review by sidharthv96 — APPROVED** [review]
Wow, @jsoref this is exemplary work! 🌟
