### PR TITLE
7000: Fix mindmap rendering issue when Level 2 nodes exceed 11

### LINKED ISSUE #7000: Mindmap rendering broken when the number of level 2 nodes exceeds 11
### Description

When creating a mindmap diagram containing more than 11 level 2 nodes, the rendering of nodes from the 12th is broken. They are all colored in black and remain disconnected from the graph.

### Steps to reproduce

The issue appears with both a standalone use of mermaid library and the Live Editor with the sample code.

### Screenshots

#

Image

### Code Sample

```text
mindmap
  root((Example))
    1
      working
    2
    3
    4
    5
    6
    7
    8
    9
    10
    11
    12
      broken
    13
    14
    15
```

### Setup

- Mermaid version: 11.11.0/11.12.0

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by darshanr0107**
## :bookmark_tabs: Summary

This PR fixes an issue where mindmap Level 2 nodes beyond the 11th rendered incorrectly.  
Affected nodes appeared in black and were disconnected from the graph
Resolves #7000

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [x] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/mermaid/src/diagrams/mindmap/mindmapDb.ts [hunk 1]
```diff
@@ -203,7 +203,7 @@ export class MindmapDB {
     // For other nodes, inherit parent's section number
     if (node.children) {
       for (const [index, child] of node.children.entries()) {
-        const childSectionNumber = node.level === 0 ? index : sectionNumber;
+        const childSectionNumber = node.level === 0 ? index % 11 : sectionNumber;
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: Where does this 11 come from?
Avoid magic numbers

**Review by sidharthv96 — CHANGES_REQUESTED** [review]

File: packages/mermaid/src/diagrams/mindmap/mindmapDb.ts (hunk 1 above)
Comment (darshanr0107) [reply packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: The number 11 comes from `MAX_SECTIONS - 1` (12 - 1), where  MAX_SECTIONS corresponds to `THEME_COLOR_LIMIT` in the theme configuration.

Comment (sidharthv96) [reply packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: Then please use those constants here instead of 11.

Comment (sidharthv96) [reply packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: Otherwise if someone increases MAX_SECTIONS, this 11 won't be changed.

File: packages/mermaid/src/diagrams/mindmap/mindmapDb.ts [hunk 2]
```diff
@@ -203,7 +204,7 @@ export class MindmapDB {
     // For other nodes, inherit parent's section number
     if (node.children) {
       for (const [index, child] of node.children.entries()) {
-        const childSectionNumber = node.level === 0 ? index : sectionNumber;
+        const childSectionNumber = node.level === 0 ? (index % MAX_SECTIONS) - 1 : sectionNumber;
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: Shouldn't it be this?

```suggestion
        const childSectionNumber = node.level === 0 ? index % (MAX_SECTIONS - 1) : sectionNumber;
```

Comment (darshanr0107) [reply packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: yes.. resolved in 61f74ffc5e08c399e49d820a675f7ca8bd5f7f11

**Review by sidharthv96 — APPROVED** [review]
