### PR TITLE
fix: getMessageAPI so it considers entity codes

### LINKED ISSUE #4983: getMessages API doesn't support Entity codes
### Description

If the messages contain entity codes, they are removed when using the `diagram.parser.yy.getMessages` API

### Steps to reproduce

copy the below mermaid syntax and use `diagram.parser.yy.getMessages` 

```
sequenceDiagram
    A->>B: I #9829; you!
    B->>A: I #9829; you #infin; times more!
```
when using ``diagram.parser.yy.getMessages`  👇🏻 

```
[
    {
        "from": "A",
        "to": "B",
        "message": "I",
        "wrap": false,
        "type": 0
    },
    {
        "from": "B",
        "to": "A",
        "message": "I",
        "wrap": false,
        "type": 0
    }
]
```

As you can see the `message `n attribute just contains the character `I`

### Screenshots

_No response_

### Code Sample

_No response_

### Setup

- Mermaid version: 10.2.3

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ad1992**
fixes https://github.com/mermaid-js/mermaid/issues/4983

## :bookmark_tabs: Summary

This issue is reproducible when using the API `diagram.parser.yy.getMessages` or `diagram.db.getMessages` API directly eg in test since the entity codes are not handled in `getDiagramFromText` API.

In mermaid it was working fine since the entity codes were being handled before calling the API `getDiagramFromText` hence I have removed that and instead handling it inside the function `getDiagramFromText`. 
I hope this should be acceptable and I have added test as well for the same.

Resolves #4983

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.
Already explained above

### :clipboard: Tasks

Already explained above

As per the lint rule failing for circular deps, I think we can move the util `encodeEntities` to `packages/mermaid/src/utils.ts` since now its a reusable common util. let me know If I should move the util.

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by ad1992** [comment]
@sidharthv96 can you take a look at the PR and share your insights 🙏

File: packages/mermaid/src/diagram-api/types.ts [hunk 1]
```diff
@@ -37,6 +45,7 @@ export interface DiagramDB {
 
   setDisplayMode?: (title: string) => void;
   bindFunctions?: (element: Element) => void;
+  getMessages?: () => Message[];
```
Comment (sidharthv96) [inline packages/mermaid/src/diagram-api/types.ts:48]: We cannot add this type to DiagramDB, as it's not a common function that each diagram shares. 
It'll have to be added to the specific diagramDB which exposes the getMessages function.

File: packages/mermaid/src/Diagram.ts [hunk 2]
```diff
@@ -5,6 +5,7 @@ import { detectType, getDiagramLoader } from './diagram-api/detectType.js';
 import { UnknownDiagramError } from './errors.js';
 import type { DetailedError } from './utils.js';
 import type { DiagramDefinition, DiagramMetadata } from './diagram-api/types.js';
+import { encodeEntities } from './mermaidAPI.js';
```
Comment (sidharthv96) [inline packages/mermaid/src/Diagram.ts:8]: > As per the lint rule failing for circular deps, I think we can move the util encodeEntities to packages/mermaid/src/utils.ts since now its a reusable common util. let me know If I should move the util.

Yes, this should be moved. 
Maybe you can move both encode and decode functions into it's own file.

File: packages/mermaid/src/diagram-api/types.ts [hunk 3]
```diff
@@ -19,6 +19,14 @@ export interface InjectUtils {
...
 }
 
+export type Message = {
+  type: number;
+  to: string;
+  from: string;
+  message: string;
+  wrap: boolean;
+};
+
```
Comment (sidharthv96) [inline packages/mermaid/src/diagram-api/types.ts:29]: This should not be in the common types.ts, but in the sequenceDiagram folder.

File: packages/mermaid/src/Diagram.ts [hunk 4]
```diff
@@ -81,6 +82,8 @@ export const getDiagramFromText = async (
   text: string,
   metadata: Pick<DiagramMetadata, 'title'> = {}
 ): Promise<Diagram> => {
+  text = encodeEntities(text);
+
```
Comment (sidharthv96) [inline packages/mermaid/src/Diagram.ts:86]: The right place for this would be inside the constructor of `mermaid/packages/mermaid/src/Diagram.ts`.

File: packages/mermaid/src/diagram.spec.ts [hunk 5]
```diff
@@ -69,4 +69,18 @@ Expecting 'TXT', got 'NEWLINE'"
...
+    A->>B: I #9829; you!
+    B->>A: I #9829; you #infin; times more!`);
+    const messages = diagram.db?.getMessages?.();
+    if (!messages) {
+      throw new Error('Messages not found!');
+    }
+    const result = ['I ﬂ°°9829¶ß you!', 'I ﬂ°°9829¶ß you ﬂ°infin¶ß times more!'];
+    messages.forEach((message, index: number) => {
+      expect(message.message).toBe(result[index]);
+    });
```
Comment (sidharthv96) [inline packages/mermaid/src/diagram.spec.ts:84]: Nothing technically wrong with the forEach, but this feels better for readability, as it's a test. 

```suggestion
    expect(messages[0].message).toBe('I ﬂ°°9829¶ß you!');
    expect(messages[1].message).toBe('I ﬂ°°9829¶ß you ﬂ°infin¶ß times more!');
```

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Happy to see tests!
If moving to constructor and splitting the functions to a different file doesn't cause issues, it should be good to go. 

Also, curious to know the usecase for directly accessing the inner functions.
These could break in a while as we switch to a new internal architecture.

File: packages/mermaid/src/diagram-api/types.ts (hunk 1 above)
Comment (ad1992) [reply packages/mermaid/src/diagram-api/types.ts:48]: This looks like will take more time as there are no types for sequenceDb so I will do that in a separate PR

File: packages/mermaid/src/Diagram.ts (hunk 4 above)
Comment (ad1992) [reply packages/mermaid/src/Diagram.ts:86]: Rethinking, I feel it should be in utils along with `decodeEntities` reason being these are pure JS functions and reusable as well so utils looks like a good place and these can be separately unit tested as well. Let me know if this sounds good.

**Comment by ad1992** [comment]
> Also, curious to know the usecase for directly accessing the inner functions.
These could break in a while as we switch to a new internal architecture.

In Excalidraw we are adding support for mermaid hence using these internal function to get the diagram data from text.

**Comment by ad1992** [comment]
@sidharthv96 I have made the changes, however I am not sure what docs I am suppose to update (its throwing lint error), could you guide me here ? Thanks!

File: packages/mermaid/src/Diagram.ts (hunk 4 above)
Comment (sidharthv96) [reply packages/mermaid/src/Diagram.ts:87]: I meant where the function is to be called, not the implementation.

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Please move the encode entities function invocation into the diagram constructor.

**Comment by sidharthv96** [comment]
@ad1992 you can run `pnpm --filter mermaid run docs:build` to fix the docs.

**Comment by ad1992** [comment]
@sidharthv96 made the changes, the PR should be good to go!

**Review by sidharthv96 — APPROVED** [review]

**Comment by sidharthv96** [comment]
Thanks @ad1992!
