### PR TITLE
6919: correct viewBox casing in Radar & Packet

### LINKED ISSUE #6919: Incorrect `viewbox` casing in Radar
### Description

When creating a radar diagram, it incorrectly sets `viewBox` attribute as `viewbox` (small `b`), which breaks SVG containment.

### Steps to reproduce

1. create radar diagram
```mermaid
---
title: "Grades"
---
radar-beta
  axis m["Math"], s["Science"], e["English"]
  axis h["History"], g["Geography"], a["Art"]
  curve a["Alice"]{85, 90, 80, 70, 75, 90}
  curve b["Bob"]{70, 75, 85, 80, 90, 85}

  max 100
  min 0
```
2. Render SVG with Mermaid Renderer
3. See the incorrect attribute

### Screenshots

**Incorrect attribute**
Image

**Correct one**
Image

### Code Sample

```text

```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by darshanr0107**
## :bookmark_tabs: Summary
This PR fixes an issue where the SVG `viewBox` attribute was incorrectly cased as `viewbox` in the Radar and Packet diagram renderers.

Resolves #6919

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [x] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/mermaid/src/diagrams/radar/renderer.ts [hunk 1]
```diff
@@ -53,11 +54,9 @@ const drawFrame = (svg: SVG, config: Required<RadarDiagramConfig>): SVGGroup =>
...
     y: config.marginTop + config.height / 2,
   };
-  // Initialize the SVG
-  svg
-    .attr('viewbox', `0 0 ${totalWidth} ${totalHeight}`)
-    .attr('width', totalWidth)
-    .attr('height', totalHeight);
+  configureSvgSize(svg, totalHeight, totalWidth, config.useMaxWidth ?? true);
+
+  svg.attr('viewBox', `0 0 ${totalWidth} ${totalHeight}`);
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/radar/renderer.ts:59]: Any reason why we're not setting viewBox inside the `configureSvgSize` function?

**Review by sidharthv96 — APPROVED** [review]

**Comment by sidharthv96** [comment]
Please add a check in rendering test to verify the casing of viewBox during all rendering tests.

**Comment by darshanr0107** [comment]
> Please add a check in rendering test to verify the casing of viewBox during all rendering tests.

resolved in 76e17ffd203939e2fee6e84d1dc389967b3b47e5
