### PR TITLE
7156:Support quoted string labels in architecture diagrams

### LINKED ISSUE #7156: Architecture String Labels
**Describe the bug**
When using quotes to wrap a label in Architecture mode, it gets a syntax error.

**To Reproduce**
1. Go to https://mermaid.live/edit#pako:eNqNUDtPwzAQ_ivRTanUVk5oTOIN6ILEgICJuoMTX1OLxo4cGwFV_zt204IEQsKDv7vv4cftoTESgYGwzVY5bJy3OKvRCa6TsFprfJ-IXqXNzng5WV3d3665HsUB7atqMJF1KoUTtRhwsuKwPNUc1onSMfzDroaXLI37ZPXojBUt_m3M_2OMiDYdIXiP-G0dzbJmd8lsljyw0Xdi42PYUxSufwn5WZA11zCF1ioJzFmPU-jQdiK2sI8BDm6LXfgzC6XEjfA7x4HrQ4j1Qj8b052TYaTtFthG7IbQ-T7MDpdKtFZ0X6xFLdHeGK8dsOJ4BLA9vAG7oPmc0iIjhFSXtKB5UN-BXQaaLBZVmVcZyQJ9mMLH8VIyL2lgKlKUBS0JWZSHT_y0n2E

Alternatively, go to https://mermaid.live/edit and enter this:

```
architecture-beta
    group api(cloud)[API]

    service db(database)["Database"] in api
    service disk1(disk)[Storage] in api
    service disk2(disk)[Storage] in api
    service server(server)[Server] in api

    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
```

Note the "Database" label is wrapped in quotes.

The error message I get is:

```
Error: Parsing failed: unexpected character: ->[<- at offset: 69, skipped 1 characters.
unexpected character: ->]<- at offset: 80, skipped 1 characters. Expecting: one of these possible Token sequences:
  1. [NEWLINE]
  2. [EOF]
but found: '"Database"'
Expecting token of type 'EOF' but found `"Database"`.
Expecting token of type ':' but found `
`.
Expecting: one of these possible Token sequences:
  1. [--]
  2. [-]
but found: '
'
Expecting token of type 'ID' but found `
`.
```

**Expected behavior**
It's expected to allow this kind of label in order to have special characters in the label.

**Desktop (please complete the following information):**
 - OS: macOS 26.0.1
 - Browser: Firefox
 - Version: 144

**Additional context**

### PR DESCRIPTION
**Pull request by darshanr0107**
## :bookmark_tabs: Summary

This PR fixes a parsing error in `architecture-beta` diagrams where labels wrapped in quotes
(e.g. ["Database"]) caused a syntax error.
Resolves #7156

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [x] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/parser/src/language/architecture/valueConverter.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export class ArchitectureValueConverter extends AbstractMermaidValueConverter {
     } else if (rule.name === 'ARCH_TEXT_ICON') {
       return input.replace(/["()]/g, '');
     } else if (rule.name === 'ARCH_TITLE') {
-      return input.replace(/[[\]]/g, '').trim();
+      return input.replace(/["'[\]]/g, '').trim();
```
Comment (omkarht) [inline packages/parser/src/language/architecture/valueConverter.ts]:
```suggestion
      let result = input.replace(/^\[|]$/g, '').trim();
      
      // Check if wrapped in quotes and remove only outer quotes
      if ((result.startsWith('"') && result.endsWith('"')) || 
          (result.startsWith("'") && result.endsWith("'"))) {
        result = result.slice(1, -1);
        // Unescape escaped quotes
        result = result.replace(/\\"/g, '"').replace(/\\'/g, "'");
      }
      
      return result.trim();;
```

**Critical Issue:**
This regex removes **ALL** quotes and apostrophes from the string, not just the outer ones. This causes problems with:
- Titles containing apostrophes: `["John's Database"]` → `Johns Database` ❌
- Titles with inner quotes: `["The "Main" API"]` → `The Main API` ❌

File: packages/parser/tests/architecture.test.ts [hunk 2]
```diff
@@ -85,4 +85,58 @@ describe('architecture', () => {
...
+            group api(cloud)["API"]
+            `;
+      const result = parse(context);
+      expectNoErrorsOrAlternatives(result);
+      expect(result.value.$type).toBe(Architecture);
+
+      const group = result.value.groups?.[0];
+      expect(group).toBeDefined();
+      expect(group?.title).toBe('API');
+    });
```
Comment (omkarht) [inline packages/parser/tests/architecture.test.ts:140]: Add the test cases for this suggestion
https://github.com/mermaid-js/mermaid/pull/7310/changes#r2686025514

File: packages/parser/src/language/architecture/valueConverter.ts (hunk 1 above)
Comment (darshanr0107) [reply packages/parser/src/language/architecture/valueConverter.ts]: resolved in 3d3868a2bf08919673adc3fab42f70626e2f161e

File: packages/parser/tests/architecture.test.ts (hunk 2 above)
Comment (darshanr0107) [reply packages/parser/tests/architecture.test.ts:140]: resolved in 3d3868a2bf08919673adc3fab42f70626e2f161e
