### PR TITLE
bug/#3251_linkStyle-can't-specify-ids Fixed

### LINKED ISSUE #3251: Bug: `linkStyle` can't specify IDs that don't exist at the point in the diagram
**Describe the bug**

If I try to specify a linkstyle with a id that exists after the current `linkStyle`, Mermaid.js throws an error.

**To Reproduce**
1. Go to https://mermaid.live/edit#pako:eNo1js0KwjAQhF8l7Lk9eI1QUPQJ6jGXpbu1wfyUdHMIpe_uijqnge9jmB2mTAwWngXXxTyuLhlN8Ok1SgtsTob8tgZsNuXE5y--mL4fjLrQQeQS0ZNO7B_oQBaO7MBqJZ6xBnHg0qFqXQmF7-QlF7Azho07wCp5bGkCK6XyX7p51EfxZx1vfqY3UQ
2. Notice error

**Expected behavior**

`linkStyles` are applied after.

**Screenshots**

**Code Sample**
If applicable, add the code sample or a link to the [live editor](https://mermaid.live).

https://mermaid.live/edit#pako:eNo1js0KwjAQhF8l7Lk9eI1QUPQJ6jGXpbu1wfyUdHMIpe_uijqnge9jmB2mTAwWngXXxTyuLhlN8Ok1SgtsTob8tgZsNuXE5y--mL4fjLrQQeQS0ZNO7B_oQBaO7MBqJZ6xBnHg0qFqXQmF7-QlF7Azho07wCp5bGkCK6XyX7p51EfxZx1vfqY3UQ

Versions: mermaid.live v9.1.3

**Additional context**

N/a

### PR DESCRIPTION
**Pull request by RounakJoshi09**
## :bookmark_tabs: Summary

In my fix, I've added a condition to handle the case where the index provided in linkStyle is greater than or equal to the length of the edges array. This provides a clear error message to the user and prevents a TypeError from occurring.

Resolves #3251

## :straight_ruler: Design Decisions

The implementation ensures that if the user attempts to apply a style to an index that exceeds the number of available edges, an error message will be displayed.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by RounakJoshi09** [comment]
Hi @Yash-Singh1 , Could you please check my approach to fix this bug. Pardon for mistakes if any . Grateful for Your Suggestion.

File: packages/mermaid/src/diagrams/flowchart/flowDb.js [hunk 1]
```diff
@@ -192,6 +192,12 @@ export const updateLinkInterpolate = function (positions, interp) {
  */
 export const updateLink = function (positions, style) {
   positions.forEach(function (pos) {
+    if (pos >= edges.length) {
```
Comment (Yash-Singh1) [inline packages/mermaid/src/diagrams/flowchart/flowDb.js:195]: We should have a testcase to make sure a non-TypeError is thrown.

File: packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js [hunk 2]
```diff
@@ -286,6 +286,14 @@ describe('[Style] when parsing', () => {
     expect(edges[0].type).toBe('arrow_point');
   });
 
+  it('should handle style definitions within number of edges', function () {
+    const res = flow.parser.parse('graph TD\n' + 'A-->B\n' + 'linkStyle 0 stroke-width:1px;');
```
Comment (Yash-Singh1) [inline packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js:290]: Let's use a template string here instead

**Review by Yash-Singh1 — APPROVED** [review]
LGTM! I left a few comments down below.

File: packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js (hunk 2 above)
Comment (RounakJoshi09) [reply packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js]: Actually I followed the convention that was present in previous code. However I have converted it into template string.

File: packages/mermaid/src/diagrams/flowchart/flowDb.js (hunk 1 above)
Comment (RounakJoshi09) [reply packages/mermaid/src/diagrams/flowchart/flowDb.js:195]: Thanks for this suggestion, Added the new test.

File: packages/mermaid/src/diagrams/flowchart/flowDb.js [hunk 3]
```diff
@@ -192,6 +192,12 @@ export const updateLinkInterpolate = function (positions, interp) {
...
+      let error = new Error(
+        `The index for linkStyle is out of bounds. (Help: Ensure that the index is within the range of existing edges.)`
+      );
+      throw error;
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/flowchart/flowDb.js:199]:
```suggestion
      throw new Error(
        `The index for linkStyle is out of bounds. (Help: Ensure that the index is within the range of existing edges.)`
      );
```

Comment (sidharthv96) [reply packages/mermaid/src/diagrams/flowchart/flowDb.js:199]: You could also add the values in the error message. 

`The index for linkStyle is out of bounds. Index ${pos} is greater than the available edges ${edges.length}.  (Help: Ensure that the index is within the range of existing edges.)`

File: packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js [hunk 4]
```diff
@@ -286,6 +286,30 @@ describe('[Style] when parsing', () => {
...
+      flow.parser.parse(`graph TD
+      A-->B
+      linkStyle 1 stroke-width:1px;`);
+      // Fail test if above expression doesn't throw anything.
+      expect(true).toBe(false);
+    } catch (e) {
+      expect(e.message).toBe(
+        `The index for linkStyle is out of bounds. (Help: Ensure that the index is within the range of existing edges.)`
+      );
+    }
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js:300]:
```suggestion
      expect(() => flow.parser.parse(`graph TD
      A-->B
      linkStyle 1 stroke-width:1px;`).toThrow('The index for linkStyle is out of bounds. (Help: Ensure that the index is within the range of existing edges.)');
```

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Nice work! Love the tests, just needs some minor fixes :)

File: packages/mermaid/src/diagrams/flowchart/flowDb.js (hunk 3 above)
Comment (RounakJoshi09) [reply packages/mermaid/src/diagrams/flowchart/flowDb.js:199]: Hi @sidharthv96 , Thanks for your valuable suggestions, 
I am using  

**The index ${pos} for linkStyle is out of bounds. Valid indices for linkStyle are between 0 and ${edges.length - 1}. (Help: Ensure that the index is within the range of existing edges.)**,

 this as an error messgae , because _above error message is not very intuitive I believe in case of 
 
 **The index for linkStyle is out of bounds. Index 1 is greater than the available edges 1.  (Help: Ensure that the index is within the range of existing edges.)**

But still if you want to me to use the above one please let me know

**Review by nirname — APPROVED** [review]
