### PR TITLE
6750: Change MindmapDB to class based architecture

### LINKED ISSUE #6750: Update mindmap diagram to use the new class-based approach in the DB
### Description

-

### Steps to reproduce

-

### Screenshots

_No response_

### Code Sample

```text

```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by darshanr0107**
## :bookmark_tabs: Summary

 - Refactors the existing Mind map implementation from a functional approach to a class-based architecture to improve code organization, maintainability, and extensibility.

 - Return a new DB object when diagramObject.db is called.
 
 -  Introduces new MindmapDB class to encapsulate database operations and state
 
 - Migrates existing functions to class methods
 
 
Resolves #6750

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [x] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/mermaid/src/diagrams/mindmap/mindmapDb.ts [hunk 1]
```diff
@@ -78,82 +14,149 @@ const nodeType = {
...
-      return nodeType.BANG;
-    case '{{':
-      return nodeType.HEXAGON;
-    default:
-      return nodeType.DEFAULT;
+} as const;
+
+export class MindmapDB {
+  private nodes: MindmapNode[] = [];
+  private cnt = 0;
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]:
```suggestion
  private count = 0;
```

**Review by sidharthv96 — APPROVED** [review]

File: .changeset/weak-files-stare.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'mermaid': patch
+---
+
+patch: updated mindmapdb to use class based approach
```
Comment (sidharthv96) [inline .changeset/weak-files-stare.md]:
```suggestion
chore: Update MindmapDB to use class based approach
```

File: packages/mermaid/src/diagrams/mindmap/mindmapDb.ts (hunk 1 above)
Comment (darshanr0107) [reply packages/mermaid/src/diagrams/mindmap/mindmapDb.ts]: Resolved in 96c21c7e54942ffc93c9b13d9f5f359f0f4c6664

File: .changeset/weak-files-stare.md (hunk 2 above)
Comment (darshanr0107) [reply .changeset/weak-files-stare.md]: Resolved in 96c21c7e54942ffc93c9b13d9f5f359f0f4c6664

**Review by shubham-mermaid — APPROVED** [review]

File: .changeset/weak-files-stare.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'mermaid': patch
+---
+
+patch: Update MindmapDB to use class based approach
```
Comment (sidharthv96) [inline .changeset/weak-files-stare.md]:
```suggestion
chore: Update MindmapDB to use class based approach
```

Comment (darshanr0107) [reply .changeset/weak-files-stare.md]: resolved in 1e5e835c41e9c11c5eb8b7e00060fc8c5392b0a3
