### PR TITLE
bug: #4905 change shiki theme to github-light

### LINKED ISSUE #4905: C4 examples highlight is unreadable
### Description

C4 examples use a highlight schema which leaves the text and background in tones in gray and that makes reading them very hard.

### Steps to reproduce

1. go to https://mermaid.js.org/syntax/c4.html#c4-container-diagram-c4container
2. check any of the examples

### Screenshots

no-contrast

### Code Sample

_No response_

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

- either change highlight so text uses regular "black" color
- or add support for C4 highlight so proper constrast is used

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by raiman264**
## :bookmark_tabs: Summary

Changes the theme of shiki to github-light in order to propertly show all text with the light background
another way around could be to change the code block background to a darker one,
please let me know if you prefer it that way.

Resolves #4905

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

before / after
image

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/docs/.vitepress/config.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { defineConfig, MarkdownOptions } from 'vitepress';
 
 const allMarkdownTransformers: MarkdownOptions = {
   // the shiki theme to highlight code blocks
-  theme: 'github-dark',
+  theme: 'github-light',
   config: async (md) => {
```
Comment (sidharthv96) [inline packages/mermaid/src/docs/.vitepress/config.ts:8]: Changing this will break the site in dark mode. We should set the value based on the dark/light mode that the site is using. You can refer the vitepress documentation to figure out how this can be done.

**Review by sidharthv96 — CHANGES_REQUESTED** [review]

File: packages/mermaid/src/docs/.vitepress/config.ts (hunk 1 above)
Comment (raiman264) [reply packages/mermaid/src/docs/.vitepress/config.ts:8]: Thanks @sidharthv96 I just found the option and updated the PR :)

**Comment by huynhicode** [comment]
@raiman264 Looks like there is a linting issue.  Can you try running `pnpm lint:fix`?
