### PR TITLE
fix(#1066): Return true if parse is success.

### LINKED ISSUE #1066: Parse method does not return a boolean
**Describe the bug**
The `mermaid.parse()` method is supposed to return a boolean when passed a string of mermaid markdown, but it is instead returning `undefined` for valid markup, and an `Uncaught` error on invalid markup.

**To Reproduce**
`mermaid.parse('graph TD\n')` = returns `undefined`
`mermaid.parse('graph TD\n{')` = returns `Uncaught {str: "Parse error on line 1...`

**Expected behavior**
Per [this section of the current documentation](http://mermaid-js.github.io/mermaid/#/usage?id=advanced-usage), 

> "The function mermaid.parse(txt) takes a text string as an argument and returns true if the text is syntactically correct and false if it is not."

`mermaid.parse('graph TD\n')` = should return `true`
`mermaid.parse('graph TD\n{')` = should return `false`

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 77.0.3865.120

### PR DESCRIPTION
**Pull request by sidharthv96**
## :bookmark_tabs: Summary

Return true if parse is success.
Resolves #1066

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
- [ ] :notebook: have added documentation (if appropriate)
- [ ] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/mermaidAPI.ts [hunk 1]
```diff
@@ -101,19 +101,16 @@ export interface RenderResult {
 
 async function parse(text: string, parseOptions?: ParseOptions): Promise<boolean | void> {
```
Comment (aloisklink) [inline packages/mermaid/src/mermaidAPI.ts:102]: Thanks for the fix!

As far as I'm aware, this function now always returns `true` or `false`, so we might as well get rid of the `void` here.

(plus, that way TypeScript will throw an error if `#1066` happens again!)

```suggestion
async function parse(text: string, parseOptions?: ParseOptions): Promise<boolean> {
```

You may want to change this locally, instead of using GitHub's UI, since I think you'll need to regenerate `docs/config/setup/modules/mermaidAPI.md`.

**Review by aloisklink — APPROVED** [review]

**Comment by sidharthv96** [comment]
Don't have my laptop with me rn. I think the CI should fix the docs if the lint fails. If not, I'll push it locally.
