### PR TITLE
6633: Log warning for blocks exceeding column width

### LINKED ISSUE #6633: Stacking blocks renders unexpected space
### Description

When trying to stack blocks of different widths using columns 1 there is an unexpected vertical space between blocks of different widths.

### Steps to reproduce

Steps to reproduce the behavior: Any set of stacked blocks with different widths greater than 2 seem to produce a space.

### Screenshots

Image

### Code Sample

```text
Link to Live Editor: https://www.mermaidchart.com/play#pako:eNqrVkrOT0lVslJKyslPztZNSi1JjMlTAILk_JzS3LxiBUMI19EKynCyMoIwnK2MlWoBatARrg

Another Live Editor Link: https://www.mermaidchart.com/play#pako:eNqrVkrOT0lVslJKyslPztZNSi1JjMlTAILk_JzS3LxiBUMI19EKynCyMoIwnK2MIQwXKxMIwxUm4gZT425lqFQLAHetGZ4
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

_No response_

### Additional Context

I expected there to be no space between blocks A,B,C,D,E,F,G etc.

### PR DESCRIPTION
**Pull request by darshanr0107**
## :bookmark_tabs: Summary

This PR introduces a validation check and corresponding warning when a block's width exceeds the configured number of columns. 
Currently, blocks that span beyond the available column count cause render unexpected spaces without clear feedback to the user.

Resolves #6633

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [x] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [ ] :butterfly: If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by darshanr0107** [comment]
> Please make changes suggested by copilot

resolved in ac976245ad9f60b7abbbe31c530197e8196ec0d6

File: packages/mermaid/src/diagrams/block/blockDB.ts [hunk 1]
```diff
@@ -92,7 +92,20 @@ export const setCssClass = function (itemIds: string, cssClassName: string) {
...
+    if (
+      typeof column === 'number' &&
+      column > 0 &&
+      block.type !== 'column-setting' &&
+      typeof block.widthInColumns === 'number' &&
+      block.widthInColumns > column
+    ) {
+      throw new Error(
+        `Block ${block.id} width ${block.widthInColumns} exceeds configured column width ${column}`
+      );
```
Comment (aloisklink) [inline packages/mermaid/src/diagrams/block/blockDB.ts]: **issue(probably blocking)**: This breaks existing `block-beta` diagrams, which I'm not really a big fan of. Since the diagram has a `-beta` tag, I think it's acceptable, but if we can avoid it, I'd recommend it!

**suggestion**: Could we maybe change this to logging a warning instead?

**Review by aloisklink — COMMENTED** [review]
I don't like that we're breaking existing diagrams, even if they have a `-beta` suffix. Would it be possible to instead log a warning?

File: packages/mermaid/src/diagrams/block/blockDB.ts (hunk 1 above)
Comment (aloisklink) [reply packages/mermaid/src/diagrams/block/blockDB.ts]: Maybe we could also change the code so that we still show the block "overflowing" the column, but the extra empty rows are removed as well :thinking:

Comment (darshanr0107) [reply packages/mermaid/src/diagrams/block/blockDB.ts]: resolved in 54640ce476bee4f13d1b06374604d96b093d12a8

File: .changeset/ninety-roses-turn.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+'mermaid': patch
+---
+
+fix:Add validation for blocks exceeding column width.
```
[the remark this answers is not in the document]
Comment (aloisklink) [reply .changeset/ninety-roses-turn.md]: Fixed by https://github.com/mermaid-js/mermaid/commit/ac976245ad9f60b7abbbe31c530197e8196ec0d6

File: packages/mermaid/src/diagrams/block/blockDB.ts [hunk 3]
```diff
@@ -92,7 +92,18 @@ export const setCssClass = function (itemIds: string, cssClassName: string) {
...
+  const column = columnSettingBlock?.columns ?? -1;
   for (const block of blockList) {
+    if (
+      typeof column === 'number' &&
+      column > 0 &&
+      block.type !== 'column-setting' &&
+      typeof block.widthInColumns === 'number' &&
+      block.widthInColumns > column
+    ) {
+      throw new Error(`width of block ${block.id} is greater than the column width`);
```
[the remark this answers is not in the document]
Comment (aloisklink) [reply packages/mermaid/src/diagrams/block/blockDB.ts]: Fixed by https://github.com/mermaid-js/mermaid/commit/ac976245ad9f60b7abbbe31c530197e8196ec0d6

File: .changeset/ninety-roses-turn.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+---
+'mermaid': patch
+---
+
+fix: Add validation for blocks exceeding column width
+
+This update adds a validation check that triggers an error message when a block's width exceeds the defined column layout.
```
Comment (aloisklink) [inline .changeset/ninety-roses-turn.md]: **suggestion**: Would it be more accurate to change the changeset to specify that we're now logging a warning instead of an error?

You can also edit the PR title and description if you agree!

```suggestion
fix: log warning for blocks exceeding column width

This update adds a validation check that logs a warning message when a block's width exceeds the defined column layout.
```

Comment (darshanr0107) [reply .changeset/ninety-roses-turn.md]: resolved in 9cef40d1644b2bd914ea30b8b1e43954bcf2e5a5
