### PR TITLE
fix: Fix useMaxWidth option for git graph

### LINKED ISSUE #3651: useMaxWidth option doesn't work with Git Graph
**Describe the bug**

`useMaxWidth` option doesn't work with Git Graph.

**To Reproduce**

1. Run `mermaid.initialize({ gitGraph: { useMaxWidth: true } })`
2. Render git graph using mermaid
3. View the rendered SVG in Dev tools
4. Check width attribute of svg tag

**Expected behavior**

`width="100%"` is set in the svg tag.

**Screenshots**

Below is an image rendered with the `useMaxWidth` option enabled.

image

**Code Sample**

I modified the demo source code ( demos/git.html ) a little.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Git Graphs Mermaid Quick Test Page</title>
    <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgo=" />
    <style>
      div.mermaid {
        /* font-family: 'trebuchet ms', verdana, arial; */
        font-family: 'Courier New', Courier, monospace !important;
      }
    </style>
  </head>

  <body>
    <h1>Git diagram demo</h1>
    <pre class="mermaid">
    gitGraph:
    options
    {
    "nodeSpacing": 50,
    "nodeRadius": 5
    }
    end
    branch master
    commit
    branch newbranch
    checkout newbranch
    commit
    commit
    checkout master
    commit
    commit
    merge newbranch
    </pre>

    <script src="./mermaid.js"></script>
    <script>     
      mermaid.initialize({
        gitGraph: { useMaxWidth: true }
      });
    </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by uttk**
## :bookmark_tabs: Summary

Fixed Git Graph to allow `useMaxWidth` option to be set.

Resolves #3651

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

File: packages/mermaid/src/diagrams/git/gitGraphRenderer.js [hunk 1]
```diff
@@ -523,7 +522,7 @@ export const draw = function (txt, id, ver, diagObj) {
   drawCommits(diagram, allCommitsDict, true);
 
   // Setup the view box and size of the svg element
-  setupGraphViewbox(undefined, diagram, gitGraphConfig.diagramPadding, conf.useMaxWidth);
+  setupGraphViewbox(undefined, diagram, gitGraphConfig.diagramPadding, gitGraphConfig.useMaxWidth);
```
Comment (sidharthv96) [inline packages/mermaid/src/diagrams/git/gitGraphRenderer.js:525]: I feel both values should be considered. 

```suggestion
  setupGraphViewbox(undefined, diagram, gitGraphConfig.diagramPadding, gitGraphConfig.useMaxWidth ?? conf.useMaxWidth);
```

Comment (uttk) [reply packages/mermaid/src/diagrams/git/gitGraphRenderer.js]: @knsv @sidharthv96 

Thanks for the review.
Fixed to use global settings.

**Review by sidharthv96 — APPROVED** [review]

**Comment by knsv** [comment]
Thanks!
